"""
Builds the standalone, publicly-hostable version of Second Look.

Starts from the already-generated second_look.html (the Artifact version) and:
  1. Wraps it as a real standalone HTML document (doctype/html/head/body) since
     nothing is hosting/wrapping it for us anymore.
  2. Swaps every claude.use("sample") AI call for a fetch() to a small backend
     (worker.js) that holds the real OpenAI API key server-side.
  3. Swaps claude.use("db") progress storage for localStorage (per-browser,
     no accounts, no server).
  4. Updates copy that referenced "your own Claude usage" (no longer true --
     it's the site owner's API budget now).

Run this AFTER second_look.html has been (re)generated by build.py, so the
wordlist/confusable-pairs/bugfixes stay in sync between both versions.
"""
import re

src = open("second_look.html").read()

head_marker = '<div class="wrap">'
idx = src.index(head_marker)
head_content = src[:idx]
body_content = src[idx:]

# ---------------------------------------------------------------------------
# 1) checkbox copy -- no longer spends the *viewer's* Claude usage -- and add
#    a small live readout of this session's actual AI token/cost usage right
#    underneath it, so it's not an invisible number only the site owner sees
#    in their OpenAI dashboard.
# ---------------------------------------------------------------------------
old_optionrow = '''      <div class="optionrow">
        <input type="checkbox" id="useAI" checked>
        <label for="useAI">Use the deeper AI check for tricky mix-ups (uses a bit of your own Claude usage, takes up to a minute)</label>
      </div>'''
new_optionrow = '''      <div class="optionrow">
        <input type="checkbox" id="useAI" checked>
        <label for="useAI">Use the deeper AI check for tricky mix-ups (takes up to a minute)</label>
      </div>
      <div class="ai-usage-info" id="aiUsageInfo" style="font-size:12px;opacity:0.7;margin:2px 0 8px;"></div>'''
assert old_optionrow in body_content, "optionrow block not found"
body_content = body_content.replace(old_optionrow, new_optionrow, 1)

# ---------------------------------------------------------------------------
# 2) inject WORKER_URL + fetch/parse helpers right after "use strict";
# ---------------------------------------------------------------------------
anchor = '(function(){\n"use strict";\n'
assert anchor in body_content, "couldn't find script start anchor"
inject = anchor + '''
/* ---------------- backend config ----------------
   Second Look needs a tiny server-side piece for the AI check, because a
   public page can't hold a real OpenAI API key (anyone viewing the page's
   source could steal it and run up your bill). worker.js in this same
   folder is that server-side piece -- deploy it once (see README-deploy.md),
   then paste the URL it gives you below. Until you do, the AI check quietly
   stays off and only the free instant/local check runs.

   This IS the real, deployed worker (confirmed alive and responding as of
   this build) -- do not reset this back to a placeholder value on a future
   rebuild. That happened once already (a rebuild
   for an unrelated feature silently dropped this real URL back to the
   placeholder, quietly turning the deeper AI check off in production with
   no error anywhere), which is exactly the kind of regression this comment
   exists to prevent. If you ever redeploy the worker to a new URL, update
   the literal string below, not just the running worker. */
var WORKER_URL = "https://second-look-ai.diya2010gupta.workers.dev";
function aiConfigured(){ return WORKER_URL && WORKER_URL.indexOf("YOUR-WORKER") === -1; }

/* ---------------- per-session cost budget ----------------
   This site's AI check is billed to YOUR OpenAI key for every visitor, so a
   public page needs a real spending guardrail, not just a polite ask. Every
   AI call reports back the exact token counts OpenAI billed for it; this
   converts those to real dollars (using OpenAI's list price -- update
   MODEL_PRICING if pricing changes) and keeps a running total in
   sessionStorage. Once one browser session crosses SESSION_BUDGET_USD, the
   AI check quietly turns itself off for the rest of that session -- the
   instant/local check keeps working either way. sessionStorage clears when
   the tab/browser closes, so this bounds one sitting, not one visitor
   forever; it's a guard against runaway/accidental usage, not abuse from
   someone deliberately opening fresh tabs -- see README-deploy.md for
   server-side options if that matters for you. */
var SESSION_BUDGET_USD = 0.20;
var MODEL_PRICING = {
  // dollars per token = list price per 1M tokens / 1,000,000 (checked Sept 2026;
  // re-check platform.openai.com/docs/pricing if these models' prices move)
  "gpt-5-mini": { input: 0.25 / 1e6, output: 2.00 / 1e6 },
  "gpt-5-nano": { input: 0.05 / 1e6, output: 0.40 / 1e6 }
};
var SESSION_USAGE_KEY = "secondlook_session_usage_v1";
function getSessionUsage(){
  try{
    var raw = JSON.parse(sessionStorage.getItem(SESSION_USAGE_KEY));
    if (raw && isFinite(raw.cost) && isFinite(raw.tokens)) return raw;
  }catch(e){}
  return { cost: 0, tokens: 0, calls: 0 };
}
function addSessionUsage(usd, tokens){
  var cur = getSessionUsage();
  var next = { cost: cur.cost + usd, tokens: cur.tokens + tokens, calls: cur.calls + 1 };
  try{ sessionStorage.setItem(SESSION_USAGE_KEY, JSON.stringify(next)); }catch(e){}
  renderAIUsage(next);
  return next;
}
function sessionBudgetLeft(){
  return SESSION_BUDGET_USD - getSessionUsage().cost;
}
function recordUsageCost(model, usage){
  if (!usage) return;
  var rate = MODEL_PRICING[model];
  if (!rate) return;
  var promptTok = usage.prompt_tokens || 0;
  var completionTok = usage.completion_tokens || 0;
  var cost = promptTok * rate.input + completionTok * rate.output;
  addSessionUsage(cost, promptTok + completionTok);
}
// Small always-visible readout of this session's real AI usage, right under
// the AI checkbox -- so "how much is this costing me" isn't a number that
// only shows up later in your OpenAI dashboard.
function renderAIUsage(usage){
  usage = usage || getSessionUsage();
  var el = document.getElementById('aiUsageInfo');
  if (!el) return;
  if (!aiConfigured()){
    el.textContent = "";
    return;
  }
  var costStr = "$" + usage.cost.toFixed(usage.cost > 0 && usage.cost < 0.01 ? 4 : 2);
  var pct = Math.min(100, Math.round((usage.cost / SESSION_BUDGET_USD) * 100));
  el.textContent = "This session's AI usage: " + usage.tokens.toLocaleString() + " tokens · " +
    costStr + " of $" + SESSION_BUDGET_USD.toFixed(2) + " session budget (" + pct + "%)";
}

function parseJsonLoose(text){
  if (!text) throw new Error("empty AI response");
  var m = text.match(/```(?:json)?\\s*([\\s\\S]*?)```/);
  if (m) text = m[1];
  var start = text.search(/[\\[{]/);
  if (start === -1) throw new Error("no JSON found in AI response");
  text = text.slice(start);
  // Object-shaped replies (handleSpokenWord's single clarification, aiWordFitsContext's
  // fits-or-not check, extractImageText's transcription) are always small and either come
  // back whole or don't -- keep the simple strict parse for those, unchanged.
  if (text[0] !== '[') return JSON.parse(text);
  // Array-shaped replies (runAIPass's full paragraph pass) are the ones long enough to run
  // into maxTokens and come back truncated mid-item, or to have one malformed item somewhere
  // in the middle. Try the fast, common-case parse first...
  try { return JSON.parse(text); } catch(e){ /* fall through to incremental recovery below */ }
  // ...and if that fails, walk the text by hand and pull out each balanced {...} object one
  // at a time, so a single bad or truncated item doesn't throw away every other item that
  // parsed fine. This still returns a real Array (so the existing Array.isArray(result) shape
  // check every caller relies on keeps working) -- it just also carries two extra properties
  // marking that recovery happened, for callers that want to say so.
  var items = [];
  var skipped = 0;
  var i = 1; // past the leading '['
  var n = text.length;
  while (i < n){
    while (i < n && text[i] !== '{' && text[i] !== ']') i++;
    if (i >= n || text[i] === ']') break;
    var objStart = i, depth = 0, inStr = false, esc = false, objEnd = -1;
    for (; i < n; i++){
      var ch = text[i];
      if (inStr){
        if (esc) esc = false;
        else if (ch === '\\\\') esc = true;
        else if (ch === '"') inStr = false;
        continue;
      }
      if (ch === '"'){ inStr = true; continue; }
      if (ch === '{') depth++;
      else if (ch === '}'){
        depth--;
        if (depth === 0){ objEnd = i; i++; break; }
      }
    }
    if (objEnd === -1){ skipped++; break; } // ran off the end mid-object -- a truncated tail
    var frag = text.slice(objStart, objEnd+1);
    try {
      var obj = JSON.parse(frag);
      if (obj && typeof obj.original === 'string' && typeof obj.suggestion === 'string') items.push(obj);
      else skipped++;
    } catch(e2){ skipped++; }
  }
  items.partial = true;
  items.skippedCount = skipped;
  return items;
}
async function callAI(prompt, model, maxTokens, image){
  if (sessionBudgetLeft() <= 0){
    var budgetErr = new Error("this session's AI budget is used up");
    budgetErr.status = 'budget';
    throw budgetErr;
  }
  var payload = { prompt: prompt, model: model, maxTokens: maxTokens };
  if (image) payload.image = image; // data: URL for a photo upload -- see worker.js's vision handling
  var resp;
  try {
    resp = await fetch(WORKER_URL + "/ai", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });
  } catch(e){
    var neterr = new Error("network error reaching AI backend");
    neterr.status = 0;
    throw neterr;
  }
  if (!resp.ok){
    var err = new Error("AI backend returned " + resp.status);
    err.status = resp.status;
    throw err;
  }
  var data = await resp.json();
  recordUsageCost(data.model || model, data.usage);
  return parseJsonLoose(data.text || "");
}
'''
body_content = body_content.replace(anchor, inject, 1)

# ---------------------------------------------------------------------------
# 3) runAIPass: claude.use("sample") -> callAI() over the worker
# ---------------------------------------------------------------------------
old_run_ai_pass = '''async function runAIPass(text, localFlags){
  var sample = null;
  try { sample = await claude.use("sample"); } catch(e){ sample = null; }
  if (!sample){
    setStatus("Deeper AI check isn't available right now — showing the instant results only.");
    showBanner('info', "AI checking isn't available in this view, so only the instant spelling check ran.");
    return;
  }
  var aiCheck = truncateForAICheck(text);
  var aiText = aiCheck.text;
  try{
    var hintFlags = localFlags.filter(function(f){ return f.end <= aiText.length; });
    var prompt = buildPrompt(aiText, hintFlags);
    var result = await sample.json(prompt, { modelTier: "complex" });
    if (!Array.isArray(result)) throw new Error("bad shape");'''
new_run_ai_pass = '''async function runAIPass(text, localFlags){
  if (!aiConfigured()){
    setStatus("Deeper AI check isn't set up yet — showing the instant results only.");
    showBanner('info', "This site's AI checking backend hasn't been configured yet (see README-deploy.md) — only the instant spelling check ran.");
    return;
  }
  var aiCheck = truncateForAICheck(text);
  var aiText = aiCheck.text;
  try{
    var hintFlags = localFlags.filter(function(f){ return f.end <= aiText.length; });
    var prompt = buildPrompt(aiText, hintFlags);
    var result = await callAI(prompt, "gpt-5-mini", 1200);
    if (!Array.isArray(result)) throw new Error("bad shape");'''
assert old_run_ai_pass in body_content, "runAIPass header not found"
body_content = body_content.replace(old_run_ai_pass, new_run_ai_pass, 1)

old_run_ai_catch = '''  }catch(e){
    var code = e && e.code;
    if (code === 'not_granted'){
      showBanner('info', "AI checking needs your permission — showing the instant results only for now.");
    } else if (code === 'rate_limited'){
      showBanner('warn', "You've used a lot of AI checks right now — try again in a bit. Instant results are still shown.");
    } else if (code === 'cancelled'){
      // no-op
    } else {
      showBanner('warn', "The deeper check hit a snag — showing the instant results only.");
    }
    setStatus("");
  }
}'''
new_run_ai_catch = '''  }catch(e){
    if (e && e.status === 'budget'){
      showBanner('info', "This session's deeper AI check budget is used up — the instant check still works great on its own. Reload the page to start a fresh session.");
    } else if (e && e.status === 429){
      showBanner('warn', "You've used a lot of AI checks right now — try again in a bit. Instant results are still shown.");
    } else if (e && e.status === 0){
      showBanner('warn', "Couldn't reach the AI backend — showing the instant results only.");
    } else {
      showBanner('warn', "The deeper check hit a snag — showing the instant results only.");
    }
    setStatus("");
  }
}'''
assert old_run_ai_catch in body_content, "runAIPass catch block not found"
body_content = body_content.replace(old_run_ai_catch, new_run_ai_catch, 1)

# ---------------------------------------------------------------------------
# 4) handleSpokenWord: same swap, quick/cheap model for the single-word ask
# ---------------------------------------------------------------------------
old_spoken = '''  popFeedback.textContent = "Thinking about how that sounds…";
  popFeedback.className = "feedback";
  var sample = null;
  try { sample = await claude.use("sample"); } catch(e){ sample = null; }
  if (!sample){
    popFeedback.textContent = "Heard “"+heard+"” — type it in if that's what you meant.";
    return;
  }
  try{
    var before = state.text.slice(Math.max(0,f.start-70), f.start);
    var after = state.text.slice(f.end, f.end+70);
    var prompt = "A student with dyslexia wrote the word \\""+f.original+"\\" in this sentence: \\""+before+"["+f.original+"]"+after+"\\". "+
      "It might be wrong. They just said the word out loud to help explain what they meant, and it sounded like \\""+heard+"\\". "+
      "Using BOTH how they spelled it and how it sounded, figure out the one correctly-spelled English word that fits the sentence. "+
      "Reply with ONLY a JSON object like {\\"suggestion\\":\\"garden\\",\\"explanation\\":\\"one short, warm sentence a child would understand\\"}.";
    var result = await sample.json(prompt, { modelTier: "quick" });
    if (result && typeof result.suggestion === 'string'){'''
new_spoken = '''  if (!aiConfigured()){
    popFeedback.textContent = "Heard “"+heard+"” — type it in if that's what you meant.";
    return;
  }
  popFeedback.textContent = "Thinking about how that sounds…";
  popFeedback.className = "feedback";
  try{
    var before = state.text.slice(Math.max(0,f.start-70), f.start);
    var after = state.text.slice(f.end, f.end+70);
    var prompt = "A student with dyslexia wrote the word \\""+f.original+"\\" in this sentence: \\""+before+"["+f.original+"]"+after+"\\". "+
      "It might be wrong. They just said the word out loud to help explain what they meant, and it sounded like \\""+heard+"\\". "+
      "Using BOTH how they spelled it and how it sounded, figure out the one correctly-spelled English word that fits the sentence. "+
      "Reply with ONLY a JSON object like {\\"suggestion\\":\\"garden\\",\\"explanation\\":\\"one short, warm sentence a child would understand\\"}.";
    var result = await callAI(prompt, "gpt-5-nano", 300);
    if (result && typeof result.suggestion === 'string'){'''
assert old_spoken in body_content, "handleSpokenWord AI block not found"
body_content = body_content.replace(old_spoken, new_spoken, 1)

# ---------------------------------------------------------------------------
# 4b) practice-sentence generator: claude.use("sample") -> callAI() over the
#     worker, on gpt-5-nano (per the practice-sentence spec: a small constrained
#     generation task doesn't need gpt-5-mini) and counted against the SAME
#     $0.20/session budget as the deeper AI check above -- there's only one
#     budget per visitor, not one per feature.
# ---------------------------------------------------------------------------
old_practice_gen = '''async function runPracticeGeneration(targets){
  var priorBatch = loadLastPracticeBatch();
  var sample = null;
  try { sample = await claude.use("sample"); } catch(e){ sample = null; }
  if (!sample){
    return { items: generateTemplateItems(targets), source: 'template', note: null };
  }
  try{
    var prompt = buildPracticePrompt(targets);
    var result = await sample.json(prompt, { modelTier: "quick" });
    var built = buildItemsFromAiReply(result, targets, priorBatch);
    if (!built) throw new Error("bad AI reply shape");
    return { items: built.items, source: built.anyTemplate ? (built.anyAi ? 'mixed' : 'template') : 'ai', note: null };
  }catch(e){
    return { items: generateTemplateItems(targets), source: 'template', note: "Couldn't reach the sentence writer — using built-in templates." };
  }
}'''
new_practice_gen = '''async function runPracticeGeneration(targets){
  var priorBatch = loadLastPracticeBatch();
  if (!aiConfigured()){
    return { items: generateTemplateItems(targets), source: 'template', note: null };
  }
  try{
    var prompt = buildPracticePrompt(targets);
    var result = await callAI(prompt, "gpt-5-nano", 600);
    var built = buildItemsFromAiReply(result, targets, priorBatch);
    if (!built) throw new Error("bad AI reply shape");
    return { items: built.items, source: built.anyTemplate ? (built.anyAi ? 'mixed' : 'template') : 'ai', note: null };
  }catch(e){
    var note = (e && e.status === 'budget')
      ? "This session's AI budget is used up — using built-in templates."
      : "Couldn't reach the sentence writer — using built-in templates.";
    return { items: generateTemplateItems(targets), source: 'template', note: note };
  }
}'''
assert old_practice_gen in body_content, "runPracticeGeneration block not found"
body_content = body_content.replace(old_practice_gen, new_practice_gen, 1)

# ---------------------------------------------------------------------------
# 4c) Write tab file upload, JPG/PNG branch: claude.use("sample") -> callAI() over the
#     worker's vision handling (real, testable against OpenAI's documented vision API,
#     unlike the Artifact build's claude.use("sample") call, whose image support is
#     unverified as of this build -- see the comment left in build.py's version of this
#     function). Billed on gpt-5-mini (the only vision-capable model in ALLOWED_MODELS)
#     against the same $0.20/session budget as everything else.
# ---------------------------------------------------------------------------
old_extract_image = '''async function extractImageText(file){
  var sample = null;
  try { sample = await claude.use("sample"); } catch(e){ sample = null; }
  if (!sample) throw new Error("Photo reading isn't available here — try a .txt file or PDF instead.");
  var dataUrl = await readFileAsDataURL(file);
  var prompt = "Read every word of text visible in this photo of a page and transcribe it exactly as written, correcting nothing. " +
    "Reply with ONLY a JSON object like {\\"text\\":\\"the transcribed text here\\"}. If a word is impossible to make out, use [?] in its place.";
  var result;
  try{
    result = await sample.json(prompt, { modelTier: "complex", image: dataUrl });
  }catch(e){
    throw new Error("Photo reading isn't available here — try a .txt file or PDF instead.");
  }
  var text = result && typeof result.text === 'string' ? result.text : null;
  if (!text) throw new Error("Couldn't read any text from that photo — try a clearer picture.");
  return text;
}'''
new_extract_image = '''async function extractImageText(file){
  if (!aiConfigured()) throw new Error("Photo reading isn't set up yet on this site (see README-deploy.md) — try a .txt file or PDF instead.");
  var dataUrl = await readFileAsDataURL(file);
  var prompt = "Read every word of text visible in this photo of a page and transcribe it exactly as written, correcting nothing. " +
    "Reply with ONLY a JSON object like {\\"text\\":\\"the transcribed text here\\"}. If a word is impossible to make out, use [?] in its place.";
  var result;
  try{
    result = await callAI(prompt, "gpt-5-mini", 2000, dataUrl);
  }catch(e){
    if (e && e.status === 'budget') throw new Error("This session's AI budget is used up — reload the page to start a fresh session, or try a .txt file or PDF instead.");
    throw new Error("Photo reading isn't available right now — try a .txt file or PDF instead.");
  }
  var text = result && typeof result.text === 'string' ? result.text : null;
  if (!text) throw new Error("Couldn't read any text from that photo — try a clearer picture.");
  return text;
}'''
assert old_extract_image in body_content, "extractImageText block not found"
body_content = body_content.replace(old_extract_image, new_extract_image, 1)

# ---------------------------------------------------------------------------
# 5) progress storage: claude.use("db") -> localStorage
# ---------------------------------------------------------------------------
old_db = '''/* ---------------- progress / db ---------------- */
var dbReady = null;
async function getDb(){
  if (dbReady === null){
    try { dbReady = await claude.use("db"); } catch(e){ dbReady = null; }
  }
  return dbReady;
}
async function loadProgress(){
  var db = await getDb();
  if (!db) return;
  try{
    var snap = await db.doc("progress/summary").get();
    var data = snap.exists && snap.data();
    if (data && Array.isArray(data.sessions)){
      state.sessions = data.sessions;
    }
    // These four are all additive fields from the practice-sentence generator --
    // absent entirely in any doc saved before this feature shipped, so each one
    // falls back to its already-set default from the state object above rather
    // than assuming it exists.
    if (data && data.wordErrors && typeof data.wordErrors === 'object') state.wordErrors = data.wordErrors;
    if (data && data.confusionErrors && typeof data.confusionErrors === 'object') state.confusionErrors = data.confusionErrors;
    if (data && data.practiceStreaks && typeof data.practiceStreaks === 'object') state.practiceStreaks = data.practiceStreaks;
    if (data && typeof data.practiceSessions === 'number') state.practiceSessions = data.practiceSessions;
    if (data && Array.isArray(data.practiceRounds)) state.practiceRounds = data.practiceRounds;
  }catch(e){}
  renderProgress();
}
async function saveProgress(){
  var db = await getDb();
  renderProgress();
  if (!db) return;
  try{
    await db.doc("progress/summary").set({
      sessions: state.sessions,
      wordErrors: state.wordErrors, confusionErrors: state.confusionErrors,
      practiceStreaks: state.practiceStreaks, practiceSessions: state.practiceSessions,
      practiceRounds: state.practiceRounds,
      updatedAt: new Date().toISOString() });
  }catch(e){}
}'''
new_db = '''/* ---------------- progress / storage ----------------
   No accounts on a public site, so progress lives in THIS browser only
   (localStorage) -- simple and private, but it won't follow a student to a
   different device or survive them clearing site data. Kept as ONE blob
   under the original key name (secondlook_sessions_v1) even now that it
   holds more than just session history -- mirrors build.py keeping
   everything in one progress/summary doc, and renaming the key would
   silently orphan any real visitor's already-saved progress. The bare-array
   branch below is exactly that old, pre-practice-feature shape. */
var PROGRESS_KEY = "secondlook_sessions_v1";
function loadProgress(){
  try{
    var raw = localStorage.getItem(PROGRESS_KEY);
    if (raw){
      var parsed = JSON.parse(raw);
      if (Array.isArray(parsed)){
        state.sessions = parsed;
      } else if (parsed && typeof parsed === 'object'){
        if (Array.isArray(parsed.sessions)) state.sessions = parsed.sessions;
        if (parsed.wordErrors && typeof parsed.wordErrors === 'object') state.wordErrors = parsed.wordErrors;
        if (parsed.confusionErrors && typeof parsed.confusionErrors === 'object') state.confusionErrors = parsed.confusionErrors;
        if (parsed.practiceStreaks && typeof parsed.practiceStreaks === 'object') state.practiceStreaks = parsed.practiceStreaks;
        if (typeof parsed.practiceSessions === 'number') state.practiceSessions = parsed.practiceSessions;
        if (Array.isArray(parsed.practiceRounds)) state.practiceRounds = parsed.practiceRounds;
      }
    }
  }catch(e){}
  renderProgress();
}
function saveProgress(){
  renderProgress();
  try{
    localStorage.setItem(PROGRESS_KEY, JSON.stringify({
      sessions: state.sessions,
      wordErrors: state.wordErrors, confusionErrors: state.confusionErrors,
      practiceStreaks: state.practiceStreaks, practiceSessions: state.practiceSessions,
      practiceRounds: state.practiceRounds
    }));
  }catch(e){}
}'''
assert old_db in body_content, "progress/db block not found"
body_content = body_content.replace(old_db, new_db, 1)

# ---------------------------------------------------------------------------
# 5b) "this looks wrong" feedback storage: db.doc("progress/feedback") ->
#     localStorage, same swap in spirit as progress/summary above -- kept in
#     its own key so it can't collide with the sessions array's shape.
# ---------------------------------------------------------------------------
old_feedback_db = '''async function loadFeedback(){
  var db = await getDb();
  if (!db) return;
  try{
    var snap = await db.doc("progress/feedback").get();
    if (snap.exists && snap.data() && Array.isArray(snap.data().feedback)){
      state.feedback = snap.data().feedback;
    }
  }catch(e){}
  renderProgress();
}
async function saveFeedback(){
  var db = await getDb();
  renderProgress();
  if (!db) return;
  try{
    await db.doc("progress/feedback").set({ feedback: state.feedback, updatedAt: new Date().toISOString() });
  }catch(e){}
}'''
new_feedback_db = '''var FEEDBACK_KEY = "secondlook_feedback_v1";
function loadFeedback(){
  try{
    var raw = localStorage.getItem(FEEDBACK_KEY);
    if (raw){
      var parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) state.feedback = parsed;
    }
  }catch(e){}
  renderProgress();
}
function saveFeedback(){
  renderProgress();
  try{ localStorage.setItem(FEEDBACK_KEY, JSON.stringify(state.feedback)); }catch(e){}
}'''
assert old_feedback_db in body_content, "progress/feedback block not found"
body_content = body_content.replace(old_feedback_db, new_feedback_db, 1)

# ---------------------------------------------------------------------------
# 5c) tag AI-sourced flags with the real model name (the shared source only
#     knows Claude's modelTier concept, not a concrete model), so a reported
#     flag records what actually produced it.
# ---------------------------------------------------------------------------
assert body_content.count("model:'ai-pass'") + body_content.count("model='ai-pass'") == 2, \
    "expected exactly 2 ai-pass model tags (new-flag push + existing-flag upgrade)"
body_content = body_content.replace("model:'ai-pass'", "model:'gpt-5-mini'").replace("model='ai-pass'", "model='gpt-5-mini'")

# ---------------------------------------------------------------------------
# 6) render the AI usage readout once on page load (matches loadProgress())
# ---------------------------------------------------------------------------
assert "loadProgress();\nloadFeedback();\n})();" in body_content, "startup call site not found"
body_content = body_content.replace("loadProgress();\nloadFeedback();\n})();", "loadProgress();\nloadFeedback();\nrenderAIUsage();\n})();", 1)

# ---------------------------------------------------------------------------
# 7) aiWordFitsContext: same swap -- quick/cheap model for the "does this
#    fit the sentence" judgment call used by "Check my fix" when a typed
#    answer is a real word but not spelling-close to the original misspelling
# ---------------------------------------------------------------------------
old_fits = '''async function aiWordFitsContext(f, candidate){
  var sample = null;
  try { sample = await claude.use("sample"); } catch(e){ sample = null; }
  if (!sample) return false;
  try{
    var before = state.text.slice(Math.max(0,f.start-70), f.start);
    var after = state.text.slice(f.end, f.end+70);
    var prompt = "A student with dyslexia originally wrote \\""+f.original+"\\" in this sentence: \\""+before+"["+f.original+"]"+after+"\\". "+
      "They're now trying the word \\""+candidate+"\\" instead of \\""+f.original+"\\". First, in one short phrase, explain what the sentence is saying and whether \\""+candidate+"\\" fits grammatically and logically in that exact spot. Then give your final verdict. "+
      "Judge ONLY whether it fits the sentence, not how close it is in spelling or sound to their original attempt. "+
      "Reply with ONLY a JSON object like {\\"reasoning\\":\\"one short phrase\\",\\"fits\\":true} or {\\"reasoning\\":\\"one short phrase\\",\\"fits\\":false}.";
    var result = await sample.json(prompt, { modelTier: "quick" });
    return !!(result && result.fits === true);
  }catch(e){ return false; }
}'''
new_fits = '''async function aiWordFitsContext(f, candidate){
  if (!aiConfigured()) return false;
  try{
    var before = state.text.slice(Math.max(0,f.start-70), f.start);
    var after = state.text.slice(f.end, f.end+70);
    var prompt = "A student with dyslexia originally wrote \\""+f.original+"\\" in this sentence: \\""+before+"["+f.original+"]"+after+"\\". "+
      "They're now trying the word \\""+candidate+"\\" instead of \\""+f.original+"\\". First, in one short phrase, explain what the sentence is saying and whether \\""+candidate+"\\" fits grammatically and logically in that exact spot. Then give your final verdict. "+
      "Judge ONLY whether it fits the sentence, not how close it is in spelling or sound to their original attempt. "+
      "Reply with ONLY a JSON object like {\\"reasoning\\":\\"one short phrase\\",\\"fits\\":true} or {\\"reasoning\\":\\"one short phrase\\",\\"fits\\":false}.";
    var result = await callAI(prompt, "gpt-5-nano", 300);
    return !!(result && result.fits === true);
  }catch(e){ return false; }
}'''
assert old_fits in body_content, "aiWordFitsContext block not found"
body_content = body_content.replace(old_fits, new_fits, 1)

# ---------------------------------------------------------------------------
# assemble a real standalone document
# ---------------------------------------------------------------------------
out = '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n'
out += head_content
out += '</head>\n<body>\n'
out += body_content
out += '</body>\n</html>\n'

open("public_index.html", "w").write(out)
print("bytes:", len(out))
print("worker configured placeholder present:", "YOUR-WORKER-SUBDOMAIN" in out)
